services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: secure_api_db
    ports:
      - "5434:5432"
    volumes:
      - secure-api-data:/var/lib/postgresql/data
    networks:
      - secure-api-network

  secure-user-api:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:password1234@db:5432/secure_api_db
      JWT_SECRET: my_super_secret_key
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123
    volumes:
      - ./certs:/app/certs
    networks:
      - secure-api-network

volumes:
  secure-api-data:

networks:
  secure-api-network:
    driver: bridge