services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: secure_api_db
    ports:
      - "5434:5432"
    volumes:
      - secure-api-data:/var/lib/postgresql/data

volumes:
  secure-api-data: