sonar.projectKey=day18-secure-user-api
sonar.projectName=day18-secure-user-api
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=node_modules/**,certs/**,.env,Dockerfile,docker-compose.yaml

sonar.host.url=http://203.159.30.224:9000
